import Head from 'next/head';

import Return from '../../components/return/Return';

export default function Sarpsborg() {
  return (
    <div>
      <Head>
        <title>Husløs pizza Manstad</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Return />
        <h1>Manstad</h1>
        <p>Se meny, åpningtider og kontaktinfo ffsf</p>
      </main>
    </div>
  );
}
