import Head from 'next/head';
import Return from '../../components/return/Return';

export default function Sarpsborg() {
  return (
    <div>
      <Head>
        <title>Husløs pizza Vikane</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Return />
        <h1 className=''>Vikane</h1>
        <p>Se meny, åpningtider og kontaktinfo</p>
      </main>
    </div>
  );
}
