import Head from 'next/head';
import Menu from '../api/apiCall';

export default function MenuSarpsborg() {
  return (
    <div>
      <Head>
        <title>Husløs pizza Sarpsborg</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div className='cardContainer'>
          <Menu />
        </div>
        <p className='allergies'>
          Allergener: E=Egg. H=Hvetegluten. P=Pinjekjerner. M=Melk. SU=sulfitt.
          SK=Skalldyr. SO=Soya.
        </p>
      </main>
    </div>
  );
}
