import Head from 'next/head';

export default function Menumanstad() {
  return (
    <div>
      <Head>
        <title>Husløs pizza Manstad</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div>xxx</div>
      </main>
    </div>
  );
}
