import Head from 'next/head';

import Agreementheading from '../components/companyagreement/Agreementheading';
import Agreementform from '../components/companyagreement/Agreementform';

function Companyagreement() {
  return (
    <div>
      <Head>
        <title>Firmaavtale Husløs Pizza</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main>
        <Agreementheading />
        <Agreementform />
      </main>
    </div>
  );
}

export default Companyagreement;
