import Head from 'next/head';

function Dashboard() {
  return (
    <div>
      <Head>
        <title>Firmaavtale Husløs Pizza</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main>You are logged in</main>
    </div>
  );
}

export default Dashboard;
