import Head from 'next/head';
import styles from '../css/Home.module.css';

import Header from '../components/header/Header';
import Herocontent from '../components/index/Herocontent';
import Pizzacontent from '../components/index/Pizzacontent';
import Ingredientscontent from '../components/index/Ingredientscontent';
import Pizzadoughcontent from '../components/index/Pizzadoughcontent';
import Missingcontent from '../components/index/Missingcontent';
import Footer from '../components/footer/Footer';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Husløs Pizza</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      <main className={styles.main}>
        <Herocontent />
        <Pizzacontent />
        <Ingredientscontent />
        <Pizzadoughcontent />
        <Missingcontent />
      </main>

      <Footer />
    </div>
  );
}
