import Head from 'next/head';
import styles from '../css/Home.module.css';

import Header from './components/header/Header';
import Footer from './components/footer/Footer';
import HeroContent from './components/index/HeroContent';
import PizzaContent from './components/index/PizzaContent';
import IngredientsContent from './components/index/IngredientsContent';
import Pizzadoughcontent from './components/index/pizzaDoughcontent';
import MissingContent from './components/index/MissingContent';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Husløs Pizza</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      <main className={styles.main}>
        <HeroContent />
        <PizzaContent />
        <IngredientsContent />
        <Pizzadoughcontent />
        <MissingContent />
      </main>

      <Footer />
    </div>
  );
}
