import Head from 'next/head';
import styles from '../css/Home.module.css';

import Header from '../components/header/Header';
import Locationsheading from '../components/locations/Locationsheading';
import Loacationsselection from '../components/locations/Locationsselection';
import Footer from '../components/footer/Footer';

export default function Locations() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Om oss</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      <main className={styles.main}>
        <Locationsheading />
        <Loacationsselection />
      </main>

      <Footer />
    </div>
  );
}
