import Head from 'next/head';
import styles from '../css/Home.module.css';

import Headercomponent from '../components/header/Headercomponent';
import Footercomponent from '../components/footer/Footercomponent';
import Locationsheading from '../components/locations/Locationsheading';
import Locationsselection from '../components/locations/Locationsselection';

export default function Locations() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Om oss</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Headercomponent />

      <main className={styles.main}>
        <Locationsheading />
        <Locationsselection />
      </main>

      <Footercomponent />
    </div>
  );
}
