import Head from 'next/head';

export default function Login() {
  return (
    <div>
      <Head>
        <title>Log in Husløs pizza</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main>
        <div>log in here</div>
      </main>
    </div>
  );
}
