import Head from 'next/head';
import styles from '../css/Home.module.css';

import Headercomponent from '../components/header/Headercomponent';
import Footercomponent from '../components/footer/Footercomponent';
import Return from '../components/return/Return';

export default function Sarpsborg() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Husløs pizza Manstad</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Headercomponent />

      <main className={styles.main}>
        <Return />
        <h1 className=''>Manstad</h1>
        <p>Se meny, åpningtider og kontaktinfo</p>
      </main>

      <Footercomponent />
    </div>
  );
}
