import Head from 'next/head';
import styles from '../css/Home.module.css';

import Return from '../components/return/Return';
import Headercomponent from '../components/header/Headercomponent';
import Footercomponent from '../components/footer/Footercomponent';
import Sarpsborgheading from '../components/sarpsborg/Sarpsborgheading';
import Sarpsborgabout from '../components/sarpsborg/Sarpsborgabout';

export default function Sarpsborg() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Husløs pizza Sarpsborg</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Headercomponent />
        <Return />
        <Sarpsborgheading />
        <Sarpsborgabout />
      </main>

      <Footercomponent />
    </div>
  );
}
